# Generated by Django 6.0.1 on 2026-01-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
