# Generated by Django 6.0.1 on 2026-02-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_celebrity_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='extra',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='celebrity',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
