# Generated by Django 6.0.1 on 2026-02-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_celebrity_extra_alter_celebrity_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='stagename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
