# Generated by Django 6.0.1 on 2026-02-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_celebrity_stagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='addinfo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='airport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
