# Generated by Django 6.0.1 on 2026-02-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_addinfo_booking_airport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='addinfo',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
