# Generated by Django 6.0.1 on 2026-02-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_addinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='event_location',
            field=models.CharField(choices=[('$5,000 - or less', '$5,000- or less'), ('$5,000 - $10,000', '$5,000 - $10,000'), ('$10,000 - $20,000', '$10,000 - $20,000'), ('$20,000 - $30,000', '$20,000 - $30,000'), ('$50,000 - $100,000', '$50,000 - $100,000'), ('$100,000 - or more', '$100,000 - or more')], default='$5,000 - or less', max_length=150),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_type',
            field=models.CharField(choices=[('Birthday', 'Birthday'), ('Meet and Greet', 'Meet and Greet'), ('Convention/Tradeshow', 'Convention/Tradeshow'), ('Cooking demo', 'Cooking demo'), ('Endorsement/Spokeperson', 'Endorsement/Spokeperson'), ('Funeral', 'Funeral'), ('Musical Perfomance', 'Musical Perfomance'), ('Personal Appearance', 'Personal Appearance'), ('Satelite Media Tour', 'Satelite Media Tour'), ('Speaking Engagement', 'Speaking Engagement'), ('Virtual Event', 'Virtual Event'), ('Weddings', 'Weddings')], default='Meet and Greet', max_length=100),
        ),
    ]
