# Generated by Django 6.0.1 on 2026-02-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='budget',
            field=models.CharField(choices=[('$5,000 - or less', '$5,000- or less'), ('$5,000 - $10,000', '$5,000 - $10,000'), ('$10,000 - $20,000', '$10,000 - $20,000'), ('$20,000 - $30,000', '$20,000 - $30,000'), ('$50,000 - $100,000', '$50,000 - $100,000'), ('$100,000 - or more', '$100,000 - or more')], default='$5,000 - or less', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event_location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
