# Generated by Django 6.0.1 on 2026-02-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_booking_budget_alter_booking_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='fbk',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='instagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='tweeter',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='youtube',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
